[project]
name = "redactions_checker_demo"
version = "0.1.0"
requires-python = ">= 3.13.2"
dependencies = [
    "dropbox>=12.0.2",
    "numpy>=2.3.5",
    "opencv-python>=4.11.0.86",
    "pillow>=12.1.0",
    "streamlit>=1.53.0",
    "streamlit-drawable-canvas>=0.9.3",
]
